env:
    browser: true
    jquery: true
extends:
  - eslint:recommended
globals:
    React: false
    ReactDOM: false
    casper: false
    require: false
rules:
    comma-dangle:
      - error
      - always-multiline
    no-multiple-empty-lines:
      - error
      - max: 2
    yoda: off
