image: phunehehe/foomail-ci
casperjs:
    script: ./test/test.sh casperjs
eslint:
    script: ./test/test.sh eslint
hlint:
    script: ./test/test.sh hlint
cabal:
    script: ./test/test.sh cabal
    artifacts:
        paths:
          - ./foomail.cabal
