ghc-options: -Wall
license: MPL-2.0
source-dirs: src

data-files: static/**/*

dependencies:
  - base
  - HaskellNet
  - HaskellNet-SSL
  - aeson
  - bytestring
  - containers
  - either
  - mime
  - record
  - resource-pool
  - servant-server
  - text
  - transformers
  - warp
  - time

executables:
  foomail:
    main: Main.hs

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
