name: foomail
version: 0.1.0.0
license: MPL-2.0
author: Hoang Xuan Phu
maintainer: phuhimself@phunehehe.net
category: Network
github: phunehehe/foomail
ghc-options: -Wall
source-dirs: src

dependencies:
  - base
  - HaskellNet
  - HaskellNet-SSL
  - aeson
  - bytestring
  - containers
  - either
  - mime
  - record
  - resource-pool
  - servant-server
  - text
  - transformers
  - warp
  - time

executables:
  foomail:
    main: Main.hs

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
